/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ks;

import software.amazon.awssdk.core.waiters.WaiterResponse;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.CreateBucketRequest;
import software.amazon.awssdk.services.s3.model.HeadBucketRequest;
import software.amazon.awssdk.services.s3.model.HeadBucketResponse;
import software.amazon.awssdk.services.s3.model.S3Exception;
import software.amazon.awssdk.services.s3.waiters.S3Waiter;

public class App {
  public static void main(String[] args) {
    App app = new App();

    Region region = Region.US_EAST_1;
    S3Client s3 = S3Client.builder().region(region).build();

    app.createBucket(s3, "kamils-bucket-xyz");
  }

  public void createBucket(S3Client s3Client, String bucketName) {

    try {
      S3Waiter s3Waiter = s3Client.waiter();
      CreateBucketRequest bucketRequest = CreateBucketRequest.builder().bucket(bucketName).build();

      s3Client.createBucket(bucketRequest);
      HeadBucketRequest bucketRequestWait = HeadBucketRequest.builder().bucket(bucketName).build();

      // Wait until the bucket is created and print out the response
      WaiterResponse<HeadBucketResponse> waiterResponse =
          s3Waiter.waitUntilBucketExists(bucketRequestWait);
      waiterResponse.matched().response().ifPresent(System.out::println);
      System.out.println(bucketName + " is ready");

    } catch (S3Exception e) {
      System.err.println(e.awsErrorDetails().errorMessage());
      System.exit(1);
    }
  }
}
